# Generated by Django 5.0.4 on 2024-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.IntegerField()),
                ('Password', models.CharField(max_length=200)),
                ('C_Password', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Registration',
                'db_table': 'Registration',
            },
        ),
    ]
